### PR TITLE
Feature/edit bug fix

### LINKED ISSUE #60: Linter Warnings Review
Go through the current app files and clean up any linter warnings.

### PR DESCRIPTION
**Pull request by C-Bandstra**
### Issue(s) related to this PR:
* closes #60 
 
 
 ### Type of change made:
* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Styling- no new features

#### If this submission is a new feature:
* [ ] Have you added an explanation of what your changes do?
* [ ] Have you lint your code locally prior to submission?

### Change Log:
* The fly form now clears when you go from editing a fly to adding a fly
* Linter warnings have been reduced.

PROBLEM:
if the user decided to edit a fly, doesnt finish, and tries to add a new fly twice. the fly form will not disappear when going back to the fly box

### Were there any challenges that arose? If so, how were the addressed?
* Every challenge imaginable. I will need some guidance for navigation bug fixes 

### Technical Debt:
* none

### Testing:
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] All new and existing tests passed?
* [ ] Have you run linter?

**Test coverage** =

### CODE REVIEW

File: containers/AddFly.js [hunk 1]
```diff
@@ -26,7 +30,7 @@ class AddFly extends Component {
         <FlyForm />
         
         <View style={{flex: 1, flexDirection: 'row', justifyContent: 'center'}}>
-          <TouchableOpacity style={styles.button}
+          <TouchableOpacity color='white' style={styles.button}
             onPress = {() => {
               this.props.clearFlyFields();
               this.props.navigation.navigate('MyFlyBox');
```
Comment (TimNguyen21) [inline containers/AddFly.js:36]: Nice! Thank you for adding this in. This will clear the Fly Form entry once a user either cancel or submit a fly.

**Comment by C-Bandstra** [comment]
I just resolved conflicts with rachael's PR
