### PR TITLE
Feature/edit bug fix

### LINKED ISSUE #53: Bug: Edit Fly
When a user clicks on the edit button on the fly box page to edit a fly, the edit fly page does not render and instead, the user sees an error message: `ReferenceError: event is not defined`

The error message is coming from EditFly.js line 17 `const selectedFly = this.props.currentFlies.find(fly => fly.id === event.target.id)`

### LINKED ISSUE #54: Bug: Fish Container Files
The associated Fish files in the container folder (FishCaught, AddFish, EditFish) had typos in their function definition and are not properly rendering.

### PR DESCRIPTION
**Pull request by C-Bandstra**
### Issue(s) related to this PR:
* closes #53 
* closes #54
 
 
 ### Type of change made:
* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Styling- no new features

#### If this submission is a new feature:
* [ ] Have you added an explanation of what your changes do?
* [ ] Have you lint your code locally prior to submission?

### Change Log:
* Typos for fish caught and edit fish are fixed
* Edit Fly no longer relies on event to grab the clicked fly
* Clicked fly id is stored in the redux store
* Added a new reducer for selectedFlyId

### Were there any challenges that arose? If so, how were the addressed?
* 

### Technical Debt:
* none

### Testing:
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] All new and existing tests passed?
* [ ] Have you run linter?

**Test coverage** =

### CODE REVIEW

File: actions/index.js [hunk 1]
```diff
@@ -21,4 +21,9 @@ export const clearFlyEntry = () => ({
 export const setCurrentFly = (data) => ({
 	type: 'SET_CURRENT_FLY',
 	data
+})
+
+export const setSelectedFlyId = (data) => ({
+	type: 'SET_FLY_ID',
+	data
```
Comment (TimNguyen21) [inline actions/index.js:28]: This is a good way to store the current Fly Id in the Redux store.  This will make the Fly Id accessible in any component in the application.  So, no need for passing props around when navigating to a different components.

File: containers/EditFly.js [hunk 2]
```diff
@@ -14,7 +14,7 @@ class EditFly extends Component {
     }
 
     componentDidMount = () => {
-        const selectedFly = this.props.currentFlies.find(fly => fly.id === event.target.id)
```
Comment (rachael-t) [inline containers/EditFly.js:17]: Great job fixing this! It has been an interesting journey going from React with the DOM to React Native and learning what items are no longer available to us since they are tied to the browser/DOM.

File: containers/FishCaught.js [hunk 3]
```diff
@@ -8,7 +8,7 @@ import {
   TouchableOpacity,
 } from "react-native";
 
-export default Fish = ({ navigation }) => {
+export default function FishCaught ({ navigation }) {
```
Comment (rachael-t) [inline containers/FishCaught.js:11]: Thanks for fixing this typo I had. It's interesting that this still was rendering properly on my Expo app on my phone when it shouldn't have due to that naming typo.
