### PR TITLE
Bug fix/fly value display

### LINKED ISSUE #66: Bug: Edit Fly Form Amount Missing
When a user clicks the button to edit a specific fly, the amount input field is displaying "Enter Fly Amount" and not the saved number. This issue is specific to native devices (I only tested on my iPhone so I'm unsure about Androids) and it works as expected on the browser version.

### LINKED ISSUE #73: Bug: Edit Fish Form Length and Weight Value Missing
When a user clicks the button to edit a specific fish, the length and weight input field is not displaying the values.

### LINKED ISSUE #74: Bug: Edit Fish Form missing Fly used to catch
When a user clicks the button to edit a specific fish, the fly used is not displayed

### PR DESCRIPTION
**Pull request by TimNguyen21**
### Issue(s) related to this PR:
* closes #66 
* closes #73 
* closes #74
 
 
 ### Type of change made:
* [x] Bugfix (non-breaking change which fixes an issue)
* [ ] New feature (non-breaking change which adds functionality)
* [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
* [ ] Styling- no new features

#### If this submission is a new feature:
* [x] Have you added an explanation of what your changes do?
* [x] Have you lint your code locally prior to submission?

### Change Log:
* components/FishForm.js - Display the correct information or value when editing a Fish
* components/FlyForm.js  - Display the correct information  or value when editing a Fly

### Were there any challenges that arose? If so, how were the addressed?
* N/A

### Technical Debt:
* N/A

### Testing:
* [ ] Have you written new tests for your core changes, as applicable?
* [ ] Have you successfully ran tests with your changes locally?
* [ ] All new and existing tests passed?
* [ ] Have you run linter?

**Test coverage** = 0

### CODE REVIEW

File: components/FishForm.js [hunk 1]
```diff
@@ -60,6 +60,15 @@ class FishForm extends Component {
     });
   };
 
+  findFlyName = () => {
```
Comment (rachael-t) [inline components/FishForm.js:63]: Great job thinking through how to address this bug!
